In [1]:
import torch

# Dot product between 2 matrix 

In [2]:
a = torch.tensor([[1,2], [2,4]], dtype = torch.int)
b = torch.tensor([1,2], dtype = torch.int)

In [3]:
ax = torch.as_tensor(a) # CONVERTING 2D MATRIX AS 1D TENSOR
bx = torch.as_tensor(b)

In [4]:
product = a @ b # WE CAN ALSO USE TORCH.MATMUL() FOR THE SAME AS @ AND MATMUL DO THE SAME THING
print(product)  # USE TORCH.DOT() IF BOTH TENSOR ARE 1D

tensor([ 5, 10], dtype=torch.int32)


# Scalar Matrix Multiplication

In [5]:
a = torch.tensor([[1,2], [3,4]])
b = 2

In [6]:
result = a * b
print(result)

tensor([[2, 4],
        [6, 8]])


# Calculate Mean by Row or Column

In [7]:
a = torch.tensor([[1,2,3], [4,5,6], [7,8,9]], dtype = float)

In [8]:
row_mean = a.mean(dim = 1)

In [9]:
column_mean = a.mean(dim = 0)

In [10]:
print(f"Row mean : {row_mean}, Column mean : {column_mean}")

Row mean : tensor([2., 5., 8.], dtype=torch.float64), Column mean : tensor([4., 5., 6.], dtype=torch.float64)


# Reshaping matrix

In [11]:
a = torch.tensor([[1,2,3,4],[5,6,7,8]])
shape = (-1,8)

In [12]:
newshape = a.reshape(shape)

In [13]:
print(newshape)

tensor([[1, 2, 3, 4, 5, 6, 7, 8]])


# Transpose of a matrix

In [14]:
a = torch.tensor([[1,2,3],[4,5,6]])

In [15]:
transpose = a.t()

In [16]:
print(transpose)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


# Matrix x Matrix

In [17]:
a = torch.tensor([[1,2],[2,4]])
b = torch.tensor([[2,1],[3,4]])

In [18]:
product = a @ b
print(product)

tensor([[ 8,  9],
        [16, 18]])


# Calculating eigen values

In [19]:
a = torch.tensor([[2,1], [1,4]], dtype=torch.float)

In [20]:
eigenvalues, eigenvectors = torch.linalg.eig(a)
print(eigenvalues, eigenvectors)

tensor([1.5858+0.j, 4.4142+0.j]) tensor([[-0.9239+0.j, -0.3827+0.j],
        [ 0.3827+0.j, -0.9239+0.j]])


# Inverse of 2x2 matrix

In [21]:
a = torch.tensor([[4, 7], [2, 6]], dtype = float)

In [22]:
inverse = torch.linalg.inv(a)

In [23]:
print(inverse)

tensor([[ 0.6000, -0.7000],
        [-0.2000,  0.4000]], dtype=torch.float64)


# SVD

In [24]:
a = torch.tensor([[2, 1], [1, 2]], dtype = float)

In [25]:
U, S, V = torch.linalg.svd(a)

In [26]:
print(U)
print(S)
print(V)

tensor([[-0.7071, -0.7071],
        [-0.7071,  0.7071]], dtype=torch.float64)
tensor([3.0000, 1.0000], dtype=torch.float64)
tensor([[-0.7071, -0.7071],
        [-0.7071,  0.7071]], dtype=torch.float64)


# Determinant of 4x4 matrix

In [30]:
A = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])


NameError: name 'long' is not defined

In [31]:
result = torch.det(A)

RuntimeError: linalg.det: Expected a floating point or complex tensor as input. Got Long